version: '3.8'

services:
  docker_controller_discord_bot:
    build: .
    image: docker_controller_discord_bot
    container_name: docker_controller_discord_bot
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TOKEN=${TOKEN}
      - PYTHONUNBUFFERED=1
